# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: ["master", "develop", "feature/automaticDeployment"]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Sourcecode
      uses: actions/checkout@v2

    - name: Setup Java for publishing to Maven Central
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'temurin'
        server-id: ossrh
        # environment variables that will contain osshr sonatype jira user and password then mvn deploy is executed
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }} # Value of the GPG private key to import
        # environment variable that will contain the passphrase for gpg-private-key then mvn deploy is executed
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Run the unit tests
      run: mvn --batch-mode test

    - name: Publish package
      run: |
        mvn --batch-mode -Dgpg.passphrase=$MAVEN_GPG_PASSPHRASE deploy
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
